from . import inherit_product_attribute
from . import inherit_sale_order
from . import inherit_sale_order_line
from . import inherit_partner
from . import inherit_stock_rule
from . import inherit_purchase_order
from . import inherit_account_move_line
from . import inherit_purchase_order_line
from . import inherit_account_move